controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    robot02_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot02_io_and_status_controller:
      type: ur_controllers/GPIOController

    robot02_speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    robot02_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robot02_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    robot02_forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    robot02_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Robotiq gripper controllers
    robot02_robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robot02_robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

robot02_speed_scaling_state_broadcaster:
  ros__parameters:
    state_publish_rate: 100.0

robot02_joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot02_shoulder_pan_joint
      - robot02_shoulder_lift_joint
      - robot02_elbow_joint
      - robot02_wrist_1_joint
      - robot02_wrist_2_joint
      - robot02_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      robot02_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

robot02_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot02_shoulder_pan_joint
      - robot02_shoulder_lift_joint
      - robot02_elbow_joint
      - robot02_wrist_1_joint
      - robot02_wrist_2_joint
      - robot02_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: ""
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      robot02_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      robot02_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

robot02_forward_velocity_controller:
  ros__parameters:
    joints:
      - robot02_shoulder_pan_joint
      - robot02_shoulder_lift_joint
      - robot02_elbow_joint
      - robot02_wrist_1_joint
      - robot02_wrist_2_joint
      - robot02_wrist_3_joint
    interface_name: velocity

robot02_forward_position_controller:
  ros__parameters:
    joints:
      - robot02_shoulder_pan_joint
      - robot02_shoulder_lift_joint
      - robot02_elbow_joint
      - robot02_wrist_1_joint
      - robot02_wrist_2_joint
      - robot02_wrist_3_joint

robot02_robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robot02_robotiq_85_left_knuckle_joint
    use_effort_interface: true
    use_speed_interface: true

robot02_robotiq_activation_controller:
  ros__parameters:
    default: true


